# Reference: https://medium.com/@developerjamiu/setting-up-ci-cd-for-flutter-apps-a841b651e70a
name: Frontend CI
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
          cache: true
      - run: flutter --version
      - name: Get Flutter packages
        run: flutter pub get
      - name: Check for lints
        run: flutter analyze
      - name: run_build_runner
        run: dart run build_runner build --delete-conflicting-outputs
#      - name: Run all tests
#        run: flutter test